defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 127.0.0.1
  username: root

development:
  <<: *defaults
  database: my_kaisen_development

test:
  <<: *defaults
  database: my_kaisen_test
