defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

development:
  <<: *defaults
  database: my_kaizen_development

test:
  <<: *defaults
  database: my_kaizen_test

production:
  <<: *defaults
  database: my_kaisen_production
